export const ESPLORA_POLLING_TIME = 5000
export const MINIMUM_BTC_REDEEMABLE = 0.00005
export const ETH_NODE_POLLING_TIME_INTERVAL = 3000
export const BTC_ESPLORA_POLLING_TIME = 3000
export const DEFAULT_DECIMALS = 18
