export const Eosio = 'eosio'
export const Ethereum = 'ethereum'
export const Bitcoin = 'bitcoin'
export const Litecoin = 'litecoin'
export const Telos = 'telos'

export const Testnet = 'testnet'
export const Mainnet = 'mainnet'

export const BitcoinMainnet = 'mainnet'
export const BitcoinTestnet = 'testnet'
export const EthereumMainnet = 'mainnet'
export const EthereumRopsten = 'testnet_ropsten'
export const EosioMainnet = 'mainnet'
export const EosioJungle3 = 'testnet_jungle3'
export const LitecoinMainnet = 'mainnet'
export const LitecoinTestnet = 'testnet'
export const TelosMainnet = 'mainnet'

export const pBTC = 'pbtc'
export const pLTC = 'pltc'
export const pETH = 'peth'
export const pWETH = 'pweth'
export const pMKR = 'pmkr'
export const pLINK = 'plink'
export const pYFI = 'pyfi'
export const PNT = 'pnt'
export const PTERIA = 'pteria'
